BookTest/Controllers/RentalsController.cs
using Bookify.Web.Core.ViewModels.BookCopy;
using Bookify.Web.Core.ViewModels.Rental;
using Bookify.Web.Core.ViewModels.Subscribers;
using Microsoft.AspNetCore.DataProtection;

namespace Bookify.Web.Controllers
{
	[Authorize(Roles = AppRole.Reception)]
	public class RentalsController : Controller
	{
		private readonly  IApplicationDbContext _context;
		private readonly IDataProtector _dataProtector;
		private readonly IMapper _mapper;

		public RentalsController(IApplicationDbContext  context, IDataProtectionProvider dataProtector, IMapper mapper)
		{
			_context = context;
			_dataProtector = dataProtector.CreateProtector("MySecureKey");
			_mapper = mapper;
		}



		[HttpGet]
		public IActionResult Create(string sKey)
		{
			var subscriberId=int.Parse(_dataProtector.Unprotect(sKey));
			var subscriber=_context.Subscribers
				.Include(s=>s.RenewalSubscribtions)
				.Include(s=>s.Rentals)
				.ThenInclude(r=>r.RentalCopies)
				.FirstOrDefault(s=>s.Id == subscriberId);
			if (subscriber is null)
				return NotFound();
			var (errorMessage, maxAllowedCopies) = ValidateSubscriber(subscriber);
			if (!string.IsNullOrEmpty(errorMessage))
				return View("NotAvailbleForRental", errorMessage);
			RentalFormViewModel model = new ()
			{
				SubscriberKey = sKey,
				CountAvailableForRental=maxAllowedCopies

			};
			return View("Form", model);
		}



		[HttpPost]

		public IActionResult Create(RentalFormViewModel model)
		{
			if (!ModelState.IsValid)
				return View("Form", model);
			var subscriberId=int.Parse(_dataProtector.Unprotect(model.SubscriberKey));
			var subscriber=_context.Subscribers
				.Include(s=>s.RenewalSubscribtions)
				.Include(s=>s.Rentals)
				.ThenInclude(r=>r.RentalCopies)
				.FirstOrDefault(s=>s.Id == subscriberId);
			if (subscriber is null)
				return NotFound();
			var (errorMessage, maxAllowedCopies) = ValidateSubscriber(subscriber);
			if (!string.IsNullOrEmpty(errorMessage))
				return View("NotAvailbleForRental", errorMessage);

			var (rentalsError, copies) = ValidateCopies(model.SelectedCopies, subscriberId);

			if (!string.IsNullOrEmpty(rentalsError))
				return View("NotAllowedRental", rentalsError);
			Rental rental = new()
			{
				RentalCopies = copies,
				CreatedById =User.GetUserId()
			};

			subscriber.Rentals.Add(rental);
			_context.SaveChanges();
			_context.SaveChanges();
			return RedirectToAction(nameof(Details), new { id = rental.Id });
		}




		public IActionResult Edit(int id)
		{
			var rental=_context.Rentals
						.Include(r=>r.RentalCopies)
						.ThenInclude(r=>r.BookCopy)
						.FirstOrDefault(r=>r.Id==id);
			if (rental is null || rental.StartDate.Date != DateTime.Today)
				return NotFound();
			var subscriber=_context.Subscribers
				.Include(s=>s.RenewalSubscribtions)
				.Include(s=>s.Rentals)
				.ThenInclude(r=>r.RentalCopies)
				.FirstOrDefault(s=>s.Id == rental.SubscriberId);

			var (errorMessage, maxAllowedCopies) = ValidateSubscriber(subscriber!, rental.Id);
			if (!string.IsNullOrEmpty(errorMessage))
				return View("NotAvailbleForRental", errorMessage);
			var currentBookCopyIds=rental.RentalCopies.Select(r=>r.BookCopyId).ToList();
			var currentBookCopy=_context.BooksCopies
									.Where(b=>currentBookCopyIds.Contains(b.Id))
									.Include(b=>b.Book)
									.ToList();
			RentalFormViewModel model = new ()
			{
				Id=rental.Id,
				SubscriberKey = _dataProtector.Protect(rental.SubscriberId.ToString()),
				CurrentCopies=_mapper.Map<IEnumerable<BookCopyViewModel>>(currentBookCopy),
				CountAvailableForRental=maxAllowedCopies

			};
			return View("Form", model);
		}

		[HttpPost]

		public IActionResult Edit(int id, RentalFormViewModel model)
		{
			if (!ModelState.IsValid) return View("Form", model);
			var rental=_context.Rentals
				.Include(r=>r.RentalCopies)
				.SingleOrDefault(r=>r.Id==model.Id);

			if (rental is null || rental.StartDate.Date != DateTime.Now.Date)
				return NotFound();

			var subscriberId=int.Parse(_dataProtector.Unprotect(model.SubscriberKey));

			var subscriber=_context.Subscribers
				.Include(s=>s.RenewalSubscribtions)
				.Include(s=>s.Rentals)
				.ThenInclude(r=>r.RentalCopies)
				.FirstOrDefault(s=>s.Id == subscriberId);
			if (subscriber is null)
				return NotFound();
			var (errorMessage, maxAllowedCopies) = ValidateSubscriber(subscriber, model.Id);
			if (!string.IsNullOrEmpty(errorMessage))
				return View("NotAvailbleForRental", errorMessage);

			var (rentalsError, copies) = ValidateCopies(model.SelectedCopies, subscriberId, rental.Id);

			if (!string.IsNullOrEmpty(rentalsError))
				return View("NotAllowedRental", rentalsError);
			rental.RentalCopies = copies;
			rental.LastUpdateById = User.GetUserId();
			rental.LastUpdateOn = DateTime.Now;

			_context.SaveChanges();


			return RedirectToAction(nameof(Details), new { id = model.Id });

		}



		public IActionResult Return(int id)
		{
			var rental = _context.Rentals
				.Include(r => r.RentalCopies)
				.ThenInclude(c => c.BookCopy)
				.ThenInclude(c => c!.Book)
				.SingleOrDefault(r => r.Id == id);

			if (rental is null || rental.CreatedOn.Date == DateTime.Today)
				return NotFound();

			var subscriber = _context.Subscribers
				.Include(s => s.RenewalSubscribtions)
				.SingleOrDefault(s => s.Id == rental.SubscriberId);

			var viewModel = new ReturnViewModel
			{
				Id = id,
				Copies = _mapper.Map<IList<RentalCopyViewModel>>(rental.RentalCopies.Where(c => !c.ReturnDate.HasValue).ToList()),
				SelectedCopies = rental.RentalCopies.Where(c => !c.ReturnDate.HasValue).Select(c => new ReturnCopyViewModel { Id = c.BookCopyId, IsReturn = c.ExtendedOn.HasValue ? false : null }).ToList(),
				AllowExtend = !subscriber!.IsBlackListed
					&& subscriber!.RenewalSubscribtions.Last().EndDate >= rental.StartDate.AddDays((int)RentalsConfigurations.MaxRentalExtended)
					&& rental.StartDate.AddDays((int)RentalsConfigurations.RentalDuration) >= DateTime.Today
			};

			return View(viewModel);
		}

		[HttpPost]

		public IActionResult Return(ReturnViewModel model)
		{
			var rental = _context.Rentals
				.Include(r => r.RentalCopies)
				.ThenInclude(c => c.BookCopy)
				.ThenInclude(c => c!.Book)
				.SingleOrDefault(r => r.Id == model.Id);

			if (rental is null || rental.CreatedOn.Date == DateTime.Today)
				return NotFound();
			if (!ModelState.IsValid)
			{
				model.Copies = _mapper.Map<IList<RentalCopyViewModel>>(rental.RentalCopies.Where(c => !c.ReturnDate.HasValue).ToList());
				return View(model);
			}
			var subscriber = _context.Subscribers
				.Include(s => s.RenewalSubscribtions)
				.SingleOrDefault(s => s.Id == rental.SubscriberId);
			if (model.SelectedCopies.Any(c => c.IsReturn.HasValue && !c.IsReturn.Value))
			{
				string error="";
				if (subscriber!.IsBlackListed)
					error = Errors.ExtendNotAllowForBlockList;
				else if (subscriber!.RenewalSubscribtions.Last().EndDate < rental.StartDate.AddDays((int)RentalsConfigurations.MaxRentalExtended))
					error = Errors.ExtendNotAllowForInActive;
				else if (rental.StartDate.AddDays((int)RentalsConfigurations.RentalDuration) < DateTime.Today)
					error = Errors.ExtendNotAllow;
				if (!string.IsNullOrEmpty(error))
				{
					model.Copies = _mapper.Map<IList<RentalCopyViewModel>>(rental.RentalCopies.Where(c => !c.ReturnDate.HasValue).ToList());
					ModelState.AddModelError("", error);
					return View(model);
				}
			}
			var isUpdated = false;

			foreach (var copy in model.SelectedCopies)
			{
				if (!copy.IsReturn.HasValue) continue;

				var currentCopy = rental.RentalCopies.SingleOrDefault(c => c.BookCopyId == copy.Id);

				if (currentCopy is null) continue;

				if (copy.IsReturn.HasValue && copy.IsReturn.Value)
				{
					if (currentCopy.ReturnDate.HasValue) continue;

					currentCopy.ReturnDate = DateTime.Now;
					isUpdated = true;
				}

				if (copy.IsReturn.HasValue && !copy.IsReturn.Value)
				{
					if (currentCopy.ExtendedOn.HasValue) continue;

					currentCopy.ExtendedOn = DateTime.Now;
					currentCopy.EndDate = currentCopy.RentalDate.AddDays((int)RentalsConfigurations.MaxRentalExtended);
					isUpdated = true;
				}
			}

			if (isUpdated)
			{
				rental.LastUpdateOn = DateTime.Now;
				rental.LastUpdateById = User.GetUserId();
				rental.PenaltyPaid = model.PenaltyPaid;

				_context.SaveChanges();
			}

			return RedirectToAction(nameof(Details), new { id = rental.Id });


		}

		[HttpPost]

		public IActionResult SearchBookCopy(SearchFormViewModel model)
		{
			if (!ModelState.IsValid) return BadRequest();
			var copy=_context.BooksCopies
				.Include(c=>c.Book)
				.SingleOrDefault(c=>c.SerialNumber.ToString()==model.Value &&!c.Book!.Deleted && !c.Deleted);
			if (copy is null)
				return NotFound(Errors.InvalidSerialNumber);
			if (!copy.IsAvailableForRental || !copy.Book!.IsAvailableForRental)
				return BadRequest(Errors.NotAvailableForRental);

			// Check If Copy Is Not  Rental  By  Another Subscribe
			var copyIsRental=_context.RentalCopies.Any(c=>c.BookCopyId==copy.Id&&!c.ReturnDate.HasValue);
			if (copyIsRental)
				return BadRequest(Errors.CopyIsInRental);
			var bookCopy=_mapper.Map<BookCopyViewModel>(copy);
			return PartialView("_CopyDetails", bookCopy);

		}


		[HttpPost]

		public IActionResult CancelRental(int id)
		{
			var rental=_context.Rentals.Find(id);
			if (rental is null || rental.StartDate.Date != DateTime.Today)
				return NotFound();
			rental.Deleted = true;
			rental.LastUpdateById = User.GetUserId();
			rental.LastUpdateOn = DateTime.Now;
			_context.SaveChanges();
			return Ok();
		}

		public IActionResult Details(int id)
		{
			var rental=_context.Rentals
				.Include(r=>r.RentalCopies)
				.ThenInclude(c=>c.BookCopy)
				.ThenInclude(b=>b!.Book)
				.SingleOrDefault(r=>r.Id==id);
			if (rental is null) return NotFound();
			RentalViewModel model=_mapper.Map<RentalViewModel>(rental);
			return View(model);
		}

BookTest/Views/Rentals/Create.cshtml
@model RentalFormViewModel

@{
    ViewData["Title"] = "Add Rental";
}

<!--begin::Card-->
<div class="card mb-7">
    <div class="card-header">
        <h3 class="card-title">Add Rental</h3>
    </div>
    <!--begin::Card body-->
    <div class="card-body">
        <partial name="_SearchBookCopy" model="new SearchFormViewModel()" />
    </div>
    <!--end::Card body-->
    <div class="card mb-5 mb-xl-8">
        <!--begin::Header-->
        <div class="card-header border-0 pt-5">
            <h3 class="card-title align-items-start flex-column">
                <span class="card-label fw-bold text-dark">Books</span>
                <span class="text-muted mt-1 fw-semibold fs-7">You can add up to @(Model.CountAvailableForRental) book(s)</span>
            </h3>
        </div>
        <!--end::Header-->
        <!--begin::Body-->
        <div class="card-body pt-5">
            <form asp-action="Create" id="CopiesForm">
                <input type="hidden" asp-for="SubscriberKey" />
                @*<input type="hidden" asp-for="SelectedBookCopiesForRental" />*@
                @* Copies will be added here *@
                <button type="submit" class="btn btn-secondary" disabled="true">
                    <span class="indicator-label">
                        Save
                    </span>
                    <span class="indicator-progress">
                        Please wait... <span class="spinner-border spinner-border-sm align-middle ms-2"></span>
                    </span>
                </button>
            </form>
        </div>
        <!--end::Body-->
    </div>
</div>
<!--end::Card-->
@section Scripts
    {
    <partial name="_ValidationScriptsPartial" />
    <script>
        var maxAllowedCopies = @(Model.CountAvailableForRental);
    </script>
    <script src="/js/rental-form.js" asp-append-version="true"></script>
    }

BookTest/Views/Rentals/Form.cshtml
@using Newtonsoft.Json;
@model RentalFormViewModel

@{
    var title= (Model.Id > 0)? "Edit" : "Add";
    ViewData["Title"] = $"{title} Rental";
}

<!--begin::Card-->
<div class="card mb-7">
    <div class="card-header">
        <h3 class="card-title">@title Rental</h3>
    </div>
    <!--begin::Card body-->
    <div class="card-body">
        <partial name="_SearchBookCopy" model="new SearchFormViewModel()" />
    </div>
    <!--end::Card body-->
    <div class="card mb-5 mb-xl-8">
        <!--begin::Header-->
        <div class="card-header border-0 pt-5">
            <h3 class="card-title align-items-start flex-column">
                <span class="card-label fw-bold text-dark">Books</span>
                <span class="text-muted mt-1 fw-semibold fs-7">You can add up to @(Model.CountAvailableForRental) book(s)</span>
            </h3>
        </div>
        <!--end::Header-->
        <!--begin::Body-->
        <div class="card-body pt-5">
            <form asp-controller="Rentals" id="CopiesForm">
                <input type="hidden" asp-for="SubscriberKey" />
                <input type="hidden" asp-for="Id"  id="rental-id"/>
                
                @foreach (var copy in Model.CurrentCopies)
                {
                    <partial name="_CopyDetails" model="@copy"/>
                }
                @* Copies will be added here *@
                <button type="submit" class="btn btn-secondary" disabled="true">
                    <span class="indicator-label">
                        Save
                    </span>
                    <span class="indicator-progress">
                        Please wait... <span class="spinner-border spinner-border-sm align-middle ms-2"></span>
                    </span>
                </button>
            </form>
        </div>
        <!--end::Body-->
    </div>
</div>
<!--end::Card-->
@section Scripts
    {
    <partial name="_ValidationScriptsPartial" />
    <script>
        var maxAllowedCopies = @(Model.CountAvailableForRental);
       
    </script>
    <script src="/js/rental-form.js" asp-append-version="true"></script>
    }

BookTest/Views/Rentals/NotAvailbleForRental.cshtml
@model string

@{
    ViewData["Title"] = "Not Allowed Rental";
}

<div class="d-flex flex-column text-center align-items-center">
    <img src="~/assets/images/stop.png" alt="stop" class="mw-200px" />

    <h4 class="bg-danger text-white display-6 w-50 rounded p-4">@Model</h4>
</div>

BookTest/Views/Rentals/Return.cshtml
@model ReturnViewModel

@{
    ViewData["Title"] = "Rental Return";
}

@if (Model.Copies.All(c => c.ReturnDate.HasValue))
{
    <div class="alert bg-light-info border border-info border-3 border-dashed d-flex flex-column flex-sm-row w-100 p-5 mt-10">
        <!--begin::Icon-->
        <!--begin::Svg Icon | path: icons/duotune/general/gen007.svg-->
        <span class="svg-icon svg-icon-2hx svg-icon-info me-4 mb-5 mb-sm-0">
            <svg width="24" height="24" viewBox="0 0 24 24" fill="none" xmlns="http://www.w3.org/2000/svg">
                <path opacity="0.3" d="M12 22C13.6569 22 15 20.6569 15 19C15 17.3431 13.6569 16 12 16C10.3431 16 9 17.3431 9 19C9 20.6569 10.3431 22 12 22Z" fill="currentColor"></path>
                <path d="M19 15V18C19 18.6 18.6 19 18 19H6C5.4 19 5 18.6 5 18V15C6.1 15 7 14.1 7 13V10C7 7.6 8.7 5.6 11 5.1V3C11 2.4 11.4 2 12 2C12.6 2 13 2.4 13 3V5.1C15.3 5.6 17 7.6 17 10V13C17 14.1 17.9 15 19 15ZM11 10C11 9.4 11.4 9 12 9C12.6 9 13 8.6 13 8C13 7.4 12.6 7 12 7C10.3 7 9 8.3 9 10C9 10.6 9.4 11 10 11C10.6 11 11 10.6 11 10Z" fill="currentColor"></path>
            </svg>
        </span>
        <!--end::Svg Icon-->
        <!--end::Icon-->
        <!--begin::Content-->
        <div class="d-flex flex-column pe-0 pe-sm-10 justify-content-center">
            <h5 class="mb-0">All copies have been returned.</h5>
        </div>
        <!--end::Content-->
    </div>
}
else
{
    <form asp-controller="Rentals">
        <div class="card pt-4 mb-6 mb-xl-9">
            <!--begin::Card header-->
            <div class="card-header border-0 pt-5">
                <h3 class="card-title align-items-start flex-column">
                    <span class="card-label fw-bold fs-3 mb-1">Books</span>
                </h3>
            </div>
            <!--end::Card header-->
            <!--begin::Card body-->
            <div class="card-body pt-0 pb-5">
                <div class="table-responsive">
                    <!--begin::Table-->
                    <table class="table align-middle gs-0 gy-4">
                        <!--begin::Table head-->
                        <thead>
                            <tr class="fw-bold text-muted bg-light">
                                <th class="ps-4 min-w-125px rounded-start">Book</th>
                                <th class="min-w-125px">Start Date</th>
                                <th class="min-w-125px">End Date</th>
                                <th class="min-w-150px">Total Delay (Days)</th>
                                <th class="min-w-150px">Return Date</th>
                                <th class="min-w-150px">Extend Date</th>
                                <th class="min-w-150px">Return</th>
                                <th class="pe-4 min-w-150px rounded-end">Extend</th>
                            </tr>
                        </thead>
                        <!--end::Table head-->
                        <!--begin::Table body-->
                        <tbody>
                            @for (var i = 0; i < Model.Copies.Count; i++)
                            {
                                var copy = Model.Copies[i];

                                <tr>
                                    <td>
                                        <div class="d-flex align-items-center ps-3">
                                            <!--begin::Symbol-->
                                            <div class="symbol symbol-40px me-5">
                                                <img src="@copy.BookCopy?.BookThumbnailURL" class="h-50 align-self-center" alt="@copy.BookCopy?.BookTitle">
                                            </div>
                                            <!--end::Symbol-->
                                            <div class="d-flex align-items-center flex-row-fluid flex-wrap">
                                                <!--begin:Author-->
                                                <div class="flex-grow-1 me-2">
                                                    <h4 class="text-gray-800 text-hover-primary fs-6 fw-bold">@copy.BookCopy?.BookTitle</h4>
                                                    <span class="text-muted fw-semibold d-block fs-7">Edition# @copy.BookCopy?.EditionNumber</span>
                                                </div>
                                                <!--end:Author-->
                                            </div>
                                            <!--end::Section-->
                                        </div>
                                    </td>
                                    <td>
                                        @copy.RentalDate.ToString("d MMM, yyyy")
                                    </td>
                                    <td>
                                        @copy.EndDate.ToString("d MMM, yyyy")
                                    </td>
                                    <td class="@(copy.DelayInDays > 0 ? "text-danger" : string.Empty)">
                                        @copy.DelayInDays Day(s)
                                    </td>
                                    <td>
                                        @copy.ReturnDate?.ToString("d MMM, yyyy")
                                    </td>
                                    <td>
                                        @copy.ExtendedOn?.ToString("d MMM, yyyy")
                                    </td>
                                    <td>
                                        <div class="form-check form-check-custom form-check-success form-check-solid">
                                            <input class="form-check-input" type="radio" value="true" asp-for="@Model.SelectedCopies[i].IsReturn" id="@($"{Model.SelectedCopies[i].Id}_true")" />
                                            <input type="hidden" asp-for="@Model.SelectedCopies[i].Id" id="@($"{Model.SelectedCopies[i].Id}_true_id")" />
                                            <label class="form-check-label" for="@($"{Model.SelectedCopies[i].Id}_true")"></label>
                                        </div>
                                    </td>
                                    <td class="text-end pe-4">
                                        <div class="form-check form-check-custom form-check-solid">
                                            <input class="form-check-input" type="radio" value="false" asp-for="@Model.SelectedCopies[i].IsReturn" id="@($"{Model.SelectedCopies[i].Id}_false")"
                                                   disabled="@(Model.AllowExtend ? null : "disabled")" />
                                            <input type="hidden" asp-for="@Model.SelectedCopies[i].Id" id="@($"{Model.SelectedCopies[i].Id}_false_id")" />
                                            <label class="form-check-label" for="@($"{Model.SelectedCopies[i].Id}_false")"></label>
                                        </div>
                                    </td>
                                </tr>
                            }
                        </tbody>
                        <!--end::Table body-->
                    </table>
                    <!--end::Table-->
                </div>
                @if (Model.TotalDelayInDays > 0)
                {
                    <div class="ps-4">
                        <div class="form-check form-check-custom form-check-solid me-10">
                            <input type="hidden" asp-for="TotalDelayInDays" />
                            <input class="form-check-input" type="checkbox" asp-for="PenaltyPaid" />
                            <label class="form-check-label" asp-for="PenaltyPaid"></label>
                        </div>
                    </div>
                }
                <div asp-validation-summary="All" class="text-danger"></div>
            </div>
            <!--end::Card body-->
            <div class="card-footer">
                <button type="submit" class="btn btn-primary">
                    <span class="indicator-label">
                        Save
                    </span>
                    <span class="indicator-progress">
                        Please wait... <span class="spinner-border spinner-border-sm align-middle ms-2"></span>
                    </span>
                </button>
            </div>
        </div>
    </form>

}

@section Scripts
    {
    <partial name="_ValidationScriptsPartial" />
}

BookTest/Views/Rentals/_CopyDetails.cshtml
@model BookCopyViewModel
<div class="js-copy-container">
<!--begin::Item-->
<div class="d-flex flex-stack">
    <input type="hidden" value="@Model.SerialNumber" data-book-id="@Model.BookId" class="js-copy" data-book-id="@Model.BookId" />
    <!--begin::Symbol-->
    <div class="symbol symbol-40px me-5">
        <img src="@Model.BookThumbnailURL" class="h-50 align-self-center" alt="@Model.BookTitle">
    </div>
    <!--end::Symbol-->
    <!--begin::Section-->
    <div class="d-flex align-items-center flex-row-fluid flex-wrap">
        <!--begin:Author-->
        <div class="flex-grow-1 me-2">
            <h4 class="text-gray-800 text-hover-primary fs-6 fw-bold">@Model.BookTitle</h4>
            <span class="text-muted fw-semibold d-block fs-7">Edition# @Model.EditionNumber</span>
        </div>
        <!--end:Author-->
        <!--begin:Action-->
        <a href="javascript:;" class="btn btn-sm btn-light-danger fs-8 fw-bold js-remove">Remove</a>
        <!--end:Action-->
    </div>
    <!--end::Section-->
</div>
<!--end::Item-->
<!--begin::Separator-->
<div class="separator separator-dashed my-4"></div>
<!--end::Separator-->
</div>

BookTest/Views/Rentals/_SearchBookCopy.cshtml
@model SearchFormViewModel


<form asp-action="SearchBookCopy"

   data-ajax-method="post"
   data-ajax="true"
   data-ajax-success="OnSerachSuccess"
   data-ajax-begin="DisabledSumitButton"
   data-ajax-failure="showErrorMessage"
   data-ajax-complete="OnmodelComplete"
      id="searchForm">
			<!--begin::Compact form-->
			<div class="d-flex align-items-center">
				<!--begin::Input group-->
				<div class="position-relative w-md-400px me-md-2">
					<!--begin::Svg Icon | path: icons/duotune/general/gen021.svg-->
					<span class="svg-icon svg-icon-3 svg-icon-gray-500 position-absolute top-50 translate-middle ms-6">
						<svg width="24" height="24" viewBox="0 0 24 24" fill="none" xmlns="http://www.w3.org/2000/svg">
							<rect opacity="0.5" x="17.0365" y="15.1223" width="8.15546" height="2" rx="1" transform="rotate(45 17.0365 15.1223)" fill="currentColor"></rect>
							<path d="M11 19C6.55556 19 3 15.4444 3 11C3 6.55556 6.55556 3 11 3C15.4444 3 19 6.55556 19 11C19 15.4444 15.4444 19 11 19ZM11 5C7.53333 5 5 7.53333 5 11C5 14.4667 7.53333 17 11 17C14.4667 17 17 14.4667 17 11C17 7.53333 14.4667 5 11 5Z" fill="currentColor"></path>
						</svg>
					</span>
					<!--end::Svg Icon-->
					<input type="text" class="form-control form-control-solid ps-10  " id="searchinput" placeholder="Search by Serial Number" asp-for="Value">
				</div>
				<!--end::Input group-->
				<!--begin:Action-->
		<div class="d-flex align-items-center">
			<button type="submit" class="btn btn-primary  js-search">
				<span class="indicator-label">
					Search
				</span>
				<span class="indicator-progress">
					Please wait... <span class="spinner-border spinner-border-sm align-middle ms-2"></span>
				</span>
			</button>
		</div>
				<!--end:Action-->
			</div>
			<!--end::Compact form-->
	
</form>